export const contributeUI = {
  en: {
    // Meta
    'contribute.meta.title': 'I Want to Contribute — Taiwan.md',
    'contribute.meta.description':
      'No programming skills needed. You can help the world understand Taiwan',

    // Hero Section
    'contribute.hero.title': 'I Want to Contribute ✋',
    'contribute.hero.subtitle':
      'No programming skills needed. Your Taiwan stories are the most valuable content.',
    'contribute.hero.note.html':
      'Current website content is initially generated by AI, expecting everyone to join forces to make information more complete and accurate!<br />If you have any questions, please feel free to <a href="mailto:cheyu.wu@monoame.com" style="color: #ABC468;">contact us</a>. Thank you for your thoughtful feedback!',

    // How It Works Section
    'contribute.how.title': '🗺️ First, understand how this website works',
    'contribute.how.language.icon': '📁',
    'contribute.how.language.title': 'Language Toggle',
    'contribute.how.language.desc.html':
      'Toggle between <strong>Chinese</strong> and <strong>English</strong> in the top-right corner. Chinese is the primary content (SSOT), English is being translated continuously.',
    'contribute.how.language.code.html':
      'taiwan.md/ → Chinese<br />taiwan.md/en/ → English',
    'contribute.how.md.icon': '📝',
    'contribute.how.md.title': '.md Button',
    'contribute.how.md.desc.html':
      "The floating <strong>.md</strong> button in the bottom-right corner of each page shows the original Markdown file. All Taiwan.md content is plain text Markdown — that's where the .md domain comes from.",
    'contribute.how.graph.icon': '🕸️',
    'contribute.how.graph.title': 'Knowledge Graph',
    'contribute.how.graph.desc':
      'The "Graph" link in the navigation leads to an interactive knowledge network diagram. Drag to explore connections between 12 aspects.',
    'contribute.how.ai.icon': '🤖',
    'contribute.how.ai.title': 'AI-Friendly',
    'contribute.how.ai.desc.html':
      'All content is fully open to AI crawlers (<a href="/robots.txt">robots.txt</a>, <a href="/llms.txt">llms.txt</a>). Feel free for ChatGPT / Claude / Gemini to cite.',

    // Roles Section
    'contribute.roles.title': "Your expertise is Taiwan's needed strength",
    'contribute.roles.desc':
      'No matter your background, you can bring unique value to this knowledge base',

    // Role: Writer
    'contribute.roles.writer.icon': '✍️',
    'contribute.roles.writer.title': 'Writers / Editors',
    'contribute.roles.writer.desc':
      'Your writing skills are the core of the knowledge base. Write new articles, improve readability of existing content, proofread typos and sentences.',
    'contribute.roles.writer.action1':
      "→ Pick a topic you're familiar with and write a warm article",
    'contribute.roles.writer.action2':
      '→ Help polish existing articles and add details',

    // Role: Researcher
    'contribute.roles.researcher.icon': '🔬',
    'contribute.roles.researcher.title': 'Researchers / Scholars',
    'contribute.roles.researcher.desc':
      'Your professional knowledge is a quality guarantee. Fact-check, add academic perspectives, point out common misconceptions.',
    'contribute.roles.researcher.action1':
      '→ Review facts and citations in articles',
    'contribute.roles.researcher.action2':
      '→ Add in-depth content from your research field',

    // Role: Designer
    'contribute.roles.designer.icon': '🎨',
    'contribute.roles.designer.title': 'Designers',
    'contribute.roles.designer.desc':
      'Good information needs good presentation. Infographics, SVG illustrations, and UI/UX improvements are all huge contributions.',
    'contribute.roles.designer.action1':
      '→ Create infographics or diagrams for articles',
    'contribute.roles.designer.action2.html':
      '→ Contribute Taiwan-themed open source icons to <a href="/en/assets">SVG Asset Library</a>',

    // Role: Engineer
    'contribute.roles.engineer.icon': '💻',
    'contribute.roles.engineer.title': 'Engineers',
    'contribute.roles.engineer.desc':
      'The website itself needs evolution. Performance optimization, new features, i18n, accessibility, SEO are all welcome.',
    'contribute.roles.engineer.action1.html':
      '→ Check if there\'s anything you can solve in <a href="https://github.com/frank890417/taiwan-md/issues" target="_blank">GitHub Issues</a>',
    'contribute.roles.engineer.action2':
      '→ Improve search, graph, multilingual features',

    // Role: Translator
    'contribute.roles.translator.icon': '🌍',
    'contribute.roles.translator.title': 'Translators',
    'contribute.roles.translator.desc':
      "Help the world understand Taiwan. Chinese to English, Chinese to Japanese, or any language — every translation expands Taiwan's visibility.",
    'contribute.roles.translator.action1.html':
      '→ Pick an article from <code>knowledge/</code> and translate to <code>knowledge/en/</code>',
    'contribute.roles.translator.action2':
      '→ Japanese version is in planning, welcome to join',

    // Role: Photographer
    'contribute.roles.photographer.icon': '📸',
    'contribute.roles.photographer.title': 'Photographers / Creators',
    'contribute.roles.photographer.desc':
      'A good photo is worth a thousand words. CC-licensed Taiwan photos, field recordings, and media materials are much needed.',
    'contribute.roles.photographer.action1':
      '→ Photograph Taiwan through your eyes, contribute with CC license',
    'contribute.roles.photographer.action2.html':
      '→ Record Taiwan sounds, join the <a href="https://github.com/frank890417/taiwan-md/tree/main/assets/sounds" target="_blank">soundscape project</a>',

    // Role: Cultural Worker
    'contribute.roles.cultural.icon': '🏛️',
    'contribute.roles.cultural.title': 'Cultural Workers / Local Experts',
    'contribute.roles.cultural.desc':
      'Your local knowledge is something AI can never generate. Oral history, local stories, cultural contexts — these are the most valuable content.',
    'contribute.roles.cultural.action1':
      "→ Write down your hometown stories, the kind textbooks don't teach",
    'contribute.roles.cultural.action2': '→ Correct local errors in articles',

    // Role: Anyone
    'contribute.roles.anyone.icon': '📢',
    'contribute.roles.anyone.title': 'Anyone who cares about Taiwan',
    'contribute.roles.anyone.desc':
      'Even if none of the above fits you, your sharing is contribution itself. Forward to friends, mention on social media, give us feedback.',
    'contribute.roles.anyone.action1':
      '→ Share taiwan.md with friends who want to understand Taiwan',
    'contribute.roles.anyone.action2':
      '→ See errors? Open an issue and tell us',

    // Organizations Section
    'contribute.org.title': '🏢 Institutions, Government Agencies & Companies',
    'contribute.org.desc':
      "Taiwan.md welcomes various organizations to participate in different ways, jointly building Taiwan's digital knowledge infrastructure.",

    // Org: Government
    'contribute.org.government.icon': '🏛️',
    'contribute.org.government.title': 'Government Agencies / Public Sector',
    'contribute.org.government.desc':
      'Provide official open data, statistics, policy documents. Help with fact-checking and content correction. License government publications or CC-licensed images.',
    'contribute.org.government.example':
      'Examples: Ministry of Culture, Tourism Bureau, Council of Indigenous Peoples, Ministry of Agriculture, Institute of History',

    // Org: Academic
    'contribute.org.academic.icon': '🎓',
    'contribute.org.academic.title': 'Academic Institutions / Research Units',
    'contribute.org.academic.desc':
      'Help write or review articles in professional fields. Provide research data and academic perspectives. Recommend students to use Taiwan.md as an open knowledge practice field.',
    'contribute.org.academic.example':
      'Examples: Academia Sinica, University Taiwan Studies Departments, Museums, Cultural Studios',

    // Org: Corporate
    'contribute.org.corporate.icon': '🏢',
    'contribute.org.corporate.title': 'Companies / Commercial Organizations',
    'contribute.org.corporate.desc':
      'Sponsor operations (servers, translation, community events). Display branding as Gold / Silver / Bronze Sponsor. Encourage employees to participate as volunteers.',
    'contribute.org.corporate.example':
      'Examples: Tech companies, Publishers, Cultural foundations, International corporate CSR',

    // Org: NGO
    'contribute.org.ngo.icon': '🌏',
    'contribute.org.ngo.title': 'NGO / International Organizations',
    'contribute.org.ngo.desc':
      'Help with multilingual translation and international promotion. Provide local perspectives on human rights, environment, social issues. Use Taiwan.md as international education resource.',
    'contribute.org.ngo.example':
      'Examples: Taiwan Foundation for Democracy, Cultural exchange associations, Overseas Taiwanese communities',

    // Org Contact
    'contribute.org.contact.title': 'Partnership Contact:',
    'contribute.org.contact.email': 'cheyu.wu@monoame.com',
    'contribute.org.contact.subject':
      'Please include "Taiwan.md Partnership — [Organization Name]" in subject line',
    'contribute.org.contact.note':
      'We will respond within 3 business days. Any form of partnership proposal is welcome.',

    // Writing Guides Section
    'contribute.guides.title': '📖 Complete Contribution Guide',
    'contribute.guides.desc':
      'No matter your background and expertise, we have the most suitable contribution method for you',

    // Guide: Writing
    'contribute.guides.writing.icon': '✍️',
    'contribute.guides.writing.title': 'How to Write a Good Article',
    'contribute.guides.writing.structure': '📐 Structure Suggestions',
    'contribute.guides.writing.structure.title':
      '<strong>Title:</strong> Clear and powerful, avoid too long (e.g.: Taiwan Night Market Culture)',
    'contribute.guides.writing.structure.opening':
      "<strong>Opening:</strong> One sentence explaining what this is and why it's important",
    'contribute.guides.writing.structure.body':
      '<strong>Body:</strong> Support with stories, data, and examples',
    'contribute.guides.writing.structure.ending':
      '<strong>Ending:</strong> Summarize significance or provide related links',
    'contribute.guides.writing.format': '📝 Format Guidelines',
    'contribute.guides.writing.format.sections.html':
      'Use <code>##</code> for sections, <code>###</code> for subsections',
    'contribute.guides.writing.format.bold.html':
      'Important terms in <code>**bold**</code>',
    'contribute.guides.writing.format.quotes.html':
      'Quotes use <code>> Quote text</code>',
    'contribute.guides.writing.format.lists.html':
      'Lists use <code>- item</code> or <code>1. numbered</code>',
    'contribute.guides.writing.format.links.html':
      'Link format: <code>[Link text](URL)</code>',
    'contribute.guides.writing.example': '💡 Example Paragraph',
    'contribute.guides.writing.example.html':
      '<pre><code>## Origins of Night Markets\n\nTaiwan\'s night market culture originated from **temple fairs during the Qing Dynasty**. Initially, vendors would gather at temple festivals to sell various snacks and daily goods.\n\n> "First府, second鹿, third艋舺" in the ancient Taiwanese saying, each place had its own unique market culture.\n\nToday\'s most famous night markets include:\n- **Shilin Night Market** (Taipei)\n- **Fengjia Night Market** (Taichung)  \n- **Liuhe Night Market** (Kaohsiung)\n\n[Learn more about night market culture](/en/food/night-markets)</code></pre>',

    // Guide: AI
    'contribute.guides.ai.icon': '🤖',
    'contribute.guides.ai.title': 'AI-Assisted Contribution',
    'contribute.guides.ai.prompt': '📋 Complete Prompt Template',
    'contribute.guides.ai.prompt.text':
      'I want to contribute content to Taiwan.md (https://taiwan.md) open Taiwan knowledge base. Please first: 1. Read https://taiwan.md/llms.txt to understand project structure 2. Read https://taiwan.md/contributing to understand editorial guidelines 3. Browse existing article categories and writing styles Then guide me through the following process: 1. Confirm my topic: [Your topic] 2. Check if there are related articles to avoid duplication 3. Plan article structure and outline 4. Help me write in Markdown format according to guidelines 5. Suggest appropriate category tags and related links 6. Check content accuracy and neutral viewpoint My knowledge background: [Describe your expertise] Topic I want to write: [Specific topic, e.g.: Taiwan coffee culture development history]',
    'contribute.guides.ai.prompts': '🎯 Professional Field AI Prompts',
    'contribute.guides.ai.prompts.historian.html':
      '<strong>Historians:</strong> "Help me fact-check this Taiwan history from multiple historical perspectives"',
    'contribute.guides.ai.prompts.cultural.html':
      '<strong>Cultural workers:</strong> "Help me introduce this Taiwan cultural phenomenon from an international perspective"',
    'contribute.guides.ai.prompts.technical.html':
      '<strong>Technical experts:</strong> "Help me explain Taiwan\'s technological development in non-technical language"',
    'contribute.guides.ai.prompts.local.html':
      '<strong>Local residents:</strong> "Help me organize hometown stories into structured articles"',

    // Guide: Translation
    'contribute.guides.translation.icon': '🌍',
    'contribute.guides.translation.title': 'Translation Guide',
    'contribute.guides.translation.keypoints':
      '🎯 Chinese→English Translation Key Points',
    'contribute.guides.translation.cultural.html':
      '<strong>Cultural terms:</strong> Keep original with annotation (e.g.: <em>jiufen (九份)</em>)',
    'contribute.guides.translation.proper.html':
      '<strong>Proper nouns:</strong> Use consistent official English names',
    'contribute.guides.translation.food.html':
      '<strong>Food names:</strong> Transliteration + explanation (<em>xiaolongbao (soup dumplings)</em>)',
    'contribute.guides.translation.historical.html':
      '<strong>Historical events:</strong> Use internationally recognized English names',
    'contribute.guides.translation.factcheck': '⚠️ Fact Checking (Required)',
    'contribute.guides.translation.factcheck.desc':
      'All articles must be fact-checked before merging. AI-assisted content is especially prone to errors (species distribution, person nationality, awards, works, etc.).',
    'contribute.guides.translation.factcheck.references.html':
      'Each article must have a <strong>References</strong> section at the end',
    'contribute.guides.translation.factcheck.numbers.html':
      'Numbers must cite <strong>source institution + year</strong>',
    'contribute.guides.translation.factcheck.priority':
      'Source priority: Official government > Academic research > Authoritative media > Professional institutions',
    'contribute.guides.translation.factcheck.errors':
      'Found errors? Welcome to submit PR corrections directly!',
    'contribute.guides.translation.resources': '📚 Reference Resources',
    'contribute.guides.translation.resources.gov.html':
      '<a href="http://www.taiwan.gov.tw/" target="_blank">Taiwan.gov.tw</a> - Official terminology',
    'contribute.guides.translation.resources.mofa.html':
      '<a href="https://www.mofa.gov.tw/en/" target="_blank">Ministry of Foreign Affairs English</a> - Political terms',
    'contribute.guides.translation.resources.tourism.html':
      '<a href="https://www.taiwan.net.tw/m1.aspx?sNo=0001019" target="_blank">Tourism Bureau</a> - Place names and attractions',
    'contribute.guides.translation.considerations':
      '⚠️ Translation Considerations',
    'contribute.guides.translation.considerations.neutral':
      'Maintain neutral and objective narrative',
    'contribute.guides.translation.considerations.localized':
      'Avoid overly localized expressions',
    'contribute.guides.translation.considerations.political':
      'Sensitive political topics require special caution',
    'contribute.guides.translation.considerations.format':
      'Numbers and date formats should follow international conventions',

    // Guide: Images
    'contribute.guides.images.icon': '📸',
    'contribute.guides.images.title': 'Image Guidelines',
    'contribute.guides.images.acceptable': '✅ Acceptable Image Sources',
    'contribute.guides.images.wikimedia.html':
      '<strong>Wikimedia Commons:</strong> Preferred, lots of Taiwan-related CC-licensed images',
    'contribute.guides.images.selftaken.html':
      '<strong>Self-taken:</strong> Best choice, remember to declare original',
    'contribute.guides.images.government.html':
      '<strong>Government open data:</strong> Most can be used freely',
    'contribute.guides.images.cc.html':
      '<strong>CC-licensed images:</strong> Must cite source and license type',
    'contribute.guides.images.recommended': '🔍 Recommended Resources',
    'contribute.guides.images.wikimedia.link.html':
      '<a href="https://commons.wikimedia.org/wiki/Category:Taiwan" target="_blank">Wikimedia Taiwan Category</a>',
    'contribute.guides.images.datagovtw.html':
      '<a href="https://data.gov.tw/" target="_blank">Government Data Open Platform</a>',
    'contribute.guides.images.unsplash.html':
      '<a href="https://unsplash.com/s/photos/taiwan" target="_blank">Unsplash Taiwan</a>',
    'contribute.guides.images.pexels.html':
      '<a href="https://www.pexels.com/search/taiwan/" target="_blank">Pexels Taiwan</a>',
    'contribute.guides.images.format': '📝 Usage Format',
    'contribute.guides.images.format.html':
      '<pre><code>![Image description](image link)\n\n*Image caption text*\n*Source: [Wikimedia Commons](link) / CC BY-SA 4.0*</code></pre>',
    'contribute.guides.images.notallowed': '❌ Cannot Use',
    'contribute.guides.images.notallowed.google':
      'Random images from Google image search',
    'contribute.guides.images.notallowed.commercial':
      'Unlicensed commercial photography',
    'contribute.guides.images.notallowed.social':
      "Photos from others' social media",
    'contribute.guides.images.notallowed.historical':
      'Historical photos with unclear copyright',

    // Paths Section
    'contribute.paths.title': 'Choose your way',

    // Path: Easy
    'contribute.paths.easy.badge': '🟢 Easiest',
    'contribute.paths.easy.title': 'Just fill out a form',
    'contribute.paths.easy.desc.html':
      "Write down what you know. A story, a fun fact, the origin of a dish.<br />We'll help with formatting, translation, and publishing.",
    'contribute.paths.easy.feature1': '✅ No account needed',
    'contribute.paths.easy.feature2': '✅ No need to know Markdown',
    'contribute.paths.easy.feature3': '✅ Can upload photos and documents',
    'contribute.paths.easy.feature4': '✅ Anonymous or credited, your choice',
    'contribute.paths.easy.button': 'Start filling ↓',

    // Path: Medium
    'contribute.paths.medium.badge': '🟡 Some barrier',
    'contribute.paths.medium.title': 'Send it to us',
    'contribute.paths.medium.desc':
      'Already have existing articles, PDFs, or photos? Send them directly.',
    'contribute.paths.medium.email.html':
      '📧 Email: <a href="mailto:cheyu.wu@monoame.com">cheyu.wu@monoame.com</a>',
    'contribute.paths.medium.github': '💬 GitHub Discussion (Chinese OK)',
    'contribute.paths.medium.button': 'Send Email →',

    // Path: AI
    'contribute.paths.ai.badge': '🤖 Let AI help you',
    'contribute.paths.ai.title': 'Talk to your AI',
    'contribute.paths.ai.desc':
      'Paste the following to ChatGPT, Claude, or Gemini, and your AI will guide you step by step to complete your contribution:',
    'contribute.paths.ai.prompt':
      'I want to contribute content to Taiwan.md (taiwan.md) open Taiwan knowledge base. Please first read https://taiwan.md/llms.txt and https://taiwan.md/contributing to understand the project structure and editorial guidelines, then guide me step by step to turn my Taiwan knowledge into a Markdown article. The topic I want to write about is: ______',
    'contribute.paths.ai.feature1': '✅ No programming skills needed',
    'contribute.paths.ai.feature2': '✅ AI will help format into Markdown',
    'contribute.paths.ai.feature3':
      '✅ Can submit via Email or PR after completion',
    'contribute.paths.ai.feature4': '✅ Supports any AI assistant',
    'contribute.paths.ai.fullprompt': 'View Full Prompt →',

    // Path: Dev
    'contribute.paths.dev.badge': '🔴 Developers',
    'contribute.paths.dev.title': 'Fork & PR',
    'contribute.paths.dev.desc.html':
      'You know Git? Great. Just add articles directly in the <code>knowledge/</code> directory.',
    'contribute.paths.dev.guide.html':
      '📖 <a href="/en/contributing">Contributing Guidelines</a>',
    'contribute.paths.dev.editorial.html':
      '📝 <a href="https://github.com/frank890417/taiwan-md/blob/main/EDITORIAL.md" target="_blank">Editorial Guidelines</a>',
    'contribute.paths.dev.button': 'Go to GitHub →',

    // Form Section
    'contribute.form.title': '📝 Share your Taiwan knowledge',
    'contribute.form.desc':
      "Fill in as much or as little as you want. One sentence is fine, a whole article is great. We'll take care of turning it into a beautiful article.",
    'contribute.form.content.label': 'What do you want to share?',
    'contribute.form.content.required': '*',
    'contribute.form.content.placeholder':
      "A story, a fun fact, the origin of a dish, the history of a place... anything goes.\n\nFor example: 'My grandma is from Changhua, she said that every Mid-Autumn Festival...'",
    'contribute.form.category.label': 'Which aspect does this belong to?',
    'contribute.form.category.unsure': "Not sure (we'll categorize it)",
    'contribute.form.category.history': '📜 History',
    'contribute.form.category.geography': '🗺️ Geography',
    'contribute.form.category.culture': '🎭 Culture',
    'contribute.form.category.food': '🍜 Food',
    'contribute.form.category.art': '🎨 Art',
    'contribute.form.category.music': '🎵 Music',
    'contribute.form.category.technology': '💻 Technology',
    'contribute.form.category.nature': '🌿 Nature',
    'contribute.form.category.people': '👥 People',
    'contribute.form.category.society': '⚖️ Society',
    'contribute.form.category.economy': '📈 Economy',
    'contribute.form.category.lifestyle': '🏠 Lifestyle',
    'contribute.form.sourcetype.label': 'How do you know this?',
    'contribute.form.sourcetype.choose': 'Choose...',
    'contribute.form.sourcetype.experience': 'Personal experience',
    'contribute.form.sourcetype.family': 'Family oral history',
    'contribute.form.sourcetype.book': 'Books',
    'contribute.form.sourcetype.internet': 'Internet',
    'contribute.form.sourcetype.professional': 'Professional background',
    'contribute.form.sourcetype.other': 'Other',
    'contribute.form.sourceref.label': 'Reference source',
    'contribute.form.sourceref.placeholder': 'Link, book title, or any clue',
    'contribute.form.name.label': 'Your name',
    'contribute.form.name.placeholder':
      "Fill if you want to be credited; leave blank for 'Anonymous Contributor'",
    'contribute.form.email.label': 'Contact info',
    'contribute.form.email.placeholder':
      'Email (if we need to confirm details with you)',
    'contribute.form.submit': 'Submit Contribution 🚀',
    'contribute.form.submitting': 'Submitting...',
    'contribute.form.success.icon': '🎉',
    'contribute.form.success.title': 'Thank you for your contribution!',
    'contribute.form.success.desc':
      "We received it. We'll organize it into an article as soon as possible and notify you when it's published (if you left an email).",
    'contribute.form.success.back': '← Back to homepage to explore more',
    'contribute.form.error':
      'Submission failed, please email directly to cheyu.wu@monoame.com',

    // Ideas Section
    'contribute.ideas.title':
      "Don't know what to write? Here's what we need most 👇",
    'contribute.ideas.hometown':
      "💬 What does your hometown have that outsiders don't know about?",
    'contribute.ideas.recipes':
      '🍜 What secret Taiwan recipes does your family have?',
    'contribute.ideas.history':
      "📖 Which Taiwan history do you know that textbooks don't cover?",
    'contribute.ideas.places':
      '🏔️ Which underrated place in Taiwan have you been to?',
    'contribute.ideas.elders':
      '👴 What stories about Taiwan have your elders told?',
    'contribute.ideas.media':
      '🎵 What Taiwan music/movies/books should foreigners know about?',

    // i18n Progress Section
    'contribute.i18n.title': '📊 Translation Progress',
    'contribute.i18n.desc':
      'Currently {coverage}% of English version is complete, thanks to all translation volunteers!',
    'contribute.i18n.english': '🇺🇸 English',
    'contribute.i18n.articles': 'articles',
    'contribute.i18n.japanese': '🇯🇵 日本語',
    'contribute.i18n.korean': '🇰🇷 한국어',
    'contribute.i18n.spanish': '🇪🇸 Español',
    'contribute.i18n.category.title': 'Category Progress',

    // Token Donation Section
    'contribute.token.title':
      '🌍 Token Donation — Use Your AI Credits to Help Taiwan Speak',
    'contribute.token.subtitle.html':
      'Have leftover Claude / ChatGPT / Gemini subscription credits each month?<br/><strong>Spend 10 minutes to add another language version to Taiwan.md.</strong>',
    'contribute.token.oneline.title': '🤖 Talk to your AI (Recommended)',
    'contribute.token.oneline.desc':
      'One command, your AI will automatically read translation guidelines, select articles, guide you through translation and submission:',
    'contribute.token.oneline.prompt':
      'Read the complete content of https://raw.githubusercontent.com/frank890417/taiwan-md/main/TRANSLATE_PROMPT.md, then guide me to translate a Taiwan.md article following the instructions.',
    'contribute.token.oneline.feature1':
      '✅ AI automatically reads latest translation guidelines and style guides',
    'contribute.token.oneline.feature2':
      '✅ Guides you to select articles and confirm target language',
    'contribute.token.oneline.feature3':
      '✅ Rewriting-based translation, not word-for-word',
    'contribute.token.oneline.feature4': '✅ Generates PR-ready Markdown files',
    'contribute.token.oneline.feature5':
      '✅ ChatGPT / Claude / Gemini all supported',
    'contribute.token.oneline.fullprompt': 'View Full Translation Prompt →',
    'contribute.token.advanced.title':
      '⚡ Advanced: Script Automation (For Developers)',
    'contribute.token.advanced.desc':
      "If you're familiar with command line, use one script to auto-scan articles, generate prompts, and submit PRs:",
    'contribute.token.languages.title': '🎯 Priority Languages',
    'contribute.token.lang.japanese': '🇯🇵 日本語',
    'contribute.token.lang.korean': '🇰🇷 한국어',
    'contribute.token.lang.spanish': '🇪🇸 Español',
    'contribute.token.lang.french': '🇫🇷 Français',
    'contribute.token.lang.german': '🇩🇪 Deutsch',
    'contribute.token.lang.vietnamese': '🇻🇳 Tiếng Việt',
    'contribute.token.lang.indonesian': '🇮🇩 Bahasa Indonesia',
    'contribute.token.lang.thai': '🇹🇭 ภาษาไทย',
    'contribute.token.guidelines.title': '📋 Complete Translation Guidelines',
    'contribute.token.guidelines.desc.html':
      'Translation helper Prompt will automatically read the latest guidelines. You can also view directly: <a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATE_PROMPT.md" target="_blank">TRANSLATE_PROMPT.md</a> | <a href="https://github.com/frank890417/taiwan-md/tree/main/i18n" target="_blank">Language-specific Style Guides</a>',
    'contribute.token.note.p1.html':
      '💡 Each language has a dedicated <a href="https://github.com/frank890417/taiwan-md/tree/main/i18n">Style Guide</a>, recording translation experience and common errors. Every correction from reviewers is written back to the Style Guide, continuously improving translation quality.',
    'contribute.token.note.p2':
      'From AI Slop to AI Supreme — not relying on one person, but on everyone worldwide who believes Taiwan deserves to be known.',
    'contribute.token.note.p3.html':
      '👉 <a href="https://github.com/frank890417/taiwan-md/discussions/137">Join Discussion</a> | Want to be a native reviewer? <a href="https://github.com/frank890417/taiwan-md/discussions/137">Sign up here</a>',

    // Copy button
    'contribute.copy.button': '📋 Copy',
    'contribute.copy.copied': '✅ Copied',
  },
  'zh-TW': {
    // Meta
    'contribute.meta.title': '我想貢獻 — Taiwan.md',
    'contribute.meta.description': '不需要會寫程式，你也能幫助世界認識台灣',

    // Hero Section
    'contribute.hero.title': '我想貢獻 ✋',
    'contribute.hero.subtitle':
      '不需要會寫程式。你知道的台灣故事，就是最珍貴的內容。',
    'contribute.hero.note.html':
      '目前網站內容由 AI 初步生成，期待集結大家的力量，讓資訊越來越完整、正確！<br />如果有問題歡迎直接<a href="mailto:cheyu.wu@monoame.com" style="color: #ABC468;">聯繫我們</a>，感謝大家這麼用心的 feedback！',

    // How It Works Section
    'contribute.how.title': '🗺️ 先了解這個網站怎麼運作',
    'contribute.how.language.icon': '📁',
    'contribute.how.language.title': '語系切換',
    'contribute.how.language.desc.html':
      '右上角可切換 <strong>中文</strong> 和 <strong>English</strong>。中文是主要內容（SSOT），英文持續翻譯中。',
    'contribute.how.language.code.html':
      'taiwan.md/ → 中文<br />taiwan.md/en/ → English',
    'contribute.how.md.icon': '📝',
    'contribute.how.md.title': '.md 按鈕',
    'contribute.how.md.desc.html':
      '每頁右下角的浮動 <strong>.md</strong> 按鈕，點擊可看到該頁的原始 Markdown 檔案。Taiwan.md 的所有內容都是純文字 Markdown — 這就是 .md 域名的由來。',
    'contribute.how.graph.icon': '🕸️',
    'contribute.how.graph.title': '知識圖譜',
    'contribute.how.graph.desc':
      '導覽列的「圖譜」連結到互動式知識網絡圖。拖拉探索 12 個面向之間的關聯。',
    'contribute.how.ai.icon': '🤖',
    'contribute.how.ai.title': 'AI-Friendly',
    'contribute.how.ai.desc.html':
      '所有內容對 AI 爬蟲完全開放（<a href="/robots.txt">robots.txt</a>、<a href="/llms.txt">llms.txt</a>）。歡迎 ChatGPT / Claude / Gemini 引用。',

    // Roles Section
    'contribute.roles.title': '你的專長，就是台灣需要的力量',
    'contribute.roles.desc':
      '不管你的背景是什麼，都能為這個知識庫帶來獨特的價值',

    // Role: Writer
    'contribute.roles.writer.icon': '✍️',
    'contribute.roles.writer.title': '寫作者 / 編輯',
    'contribute.roles.writer.desc':
      '你的文字能力是知識庫的核心。撰寫新文章、改善現有內容的可讀性、校對錯字與語句。',
    'contribute.roles.writer.action1': '→ 挑一篇你熟悉的主題，寫出有溫度的文章',
    'contribute.roles.writer.action2': '→ 幫現有文章潤稿、補充細節',

    // Role: Researcher
    'contribute.roles.researcher.icon': '🔬',
    'contribute.roles.researcher.title': '研究者 / 學者',
    'contribute.roles.researcher.desc':
      '你的專業知識是品質的保證。事實查核、補充學術觀點、指出常見迷思。',
    'contribute.roles.researcher.action1': '→ 審核文章中的事實與引用來源',
    'contribute.roles.researcher.action2': '→ 補充你研究領域的深度內容',

    // Role: Designer
    'contribute.roles.designer.icon': '🎨',
    'contribute.roles.designer.title': '設計師',
    'contribute.roles.designer.desc':
      '好的資訊需要好的呈現。資訊圖表、SVG 插圖、UI/UX 改善都是巨大的貢獻。',
    'contribute.roles.designer.action1': '→ 為文章製作資訊圖表或示意圖',
    'contribute.roles.designer.action2.html':
      '→ 到 <a href="/assets">SVG 素材庫</a> 貢獻台灣主題的開源圖示',

    // Role: Engineer
    'contribute.roles.engineer.icon': '💻',
    'contribute.roles.engineer.title': '工程師',
    'contribute.roles.engineer.desc':
      '網站本身也需要進化。效能優化、新功能、i18n、無障礙、SEO 都歡迎。',
    'contribute.roles.engineer.action1.html':
      '→ 看看 <a href="https://github.com/frank890417/taiwan-md/issues" target="_blank">GitHub Issues</a> 有沒有你能解的',
    'contribute.roles.engineer.action2': '→ 改善搜尋、圖譜、多語系等功能',

    // Role: Translator
    'contribute.roles.translator.icon': '🌍',
    'contribute.roles.translator.title': '翻譯者',
    'contribute.roles.translator.desc':
      '讓世界讀懂台灣。中翻英、中翻日、或任何語言，每一篇翻譯都在拓展台灣的能見度。',
    'contribute.roles.translator.action1.html':
      '→ 從 <code>knowledge/</code> 挑一篇翻譯到 <code>knowledge/en/</code>',
    'contribute.roles.translator.action2': '→ 日文版正在籌備中，歡迎加入',

    // Role: Photographer
    'contribute.roles.photographer.icon': '📸',
    'contribute.roles.photographer.title': '攝影師 / 創作者',
    'contribute.roles.photographer.desc':
      '一張好照片勝過千言萬語。CC 授權的台灣照片、田野錄音、影像素材都非常需要。',
    'contribute.roles.photographer.action1':
      '→ 拍下你眼中的台灣，以 CC 授權貢獻',
    'contribute.roles.photographer.action2.html':
      '→ 錄製台灣的聲音，加入<a href="https://github.com/frank890417/taiwan-md/tree/main/assets/sounds" target="_blank">聲景計畫</a>',

    // Role: Cultural Worker
    'contribute.roles.cultural.icon': '🏛️',
    'contribute.roles.cultural.title': '文史工作者 / 在地達人',
    'contribute.roles.cultural.desc':
      '你的在地知識是 AI 永遠生不出來的。口述歷史、地方故事、文化脈絡，這些是最珍貴的內容。',
    'contribute.roles.cultural.action1':
      '→ 寫下你家鄉的故事，教科書不會教的那種',
    'contribute.roles.cultural.action2': '→ 指正文章中的在地錯誤',

    // Role: Anyone
    'contribute.roles.anyone.icon': '📢',
    'contribute.roles.anyone.title': '任何關心台灣的人',
    'contribute.roles.anyone.desc':
      '就算以上都不是你，你的分享本身就是貢獻。轉發給朋友、在社群提到、給我們回饋。',
    'contribute.roles.anyone.action1': '→ 分享 taiwan.md 給想認識台灣的朋友',
    'contribute.roles.anyone.action2': '→ 看到錯誤？開 Issue 告訴我們',

    // Organizations Section
    'contribute.org.title': '🏢 機構、政府單位與企業',
    'contribute.org.desc':
      'Taiwan.md 歡迎各類組織以不同形式參與，共同建構台灣的數位知識基礎建設。',

    // Org: Government
    'contribute.org.government.icon': '🏛️',
    'contribute.org.government.title': '政府機關 / 公部門',
    'contribute.org.government.desc':
      '提供官方開放資料、統計數據、政策文件。協助事實查核與內容校正。授權使用政府出版品內容或 CC 授權圖片。',
    'contribute.org.government.example':
      '例：文化部、觀光署、原民會、農業部、國史館',

    // Org: Academic
    'contribute.org.academic.icon': '🎓',
    'contribute.org.academic.title': '學術機構 / 研究單位',
    'contribute.org.academic.desc':
      '協助撰寫或審核專業領域文章。提供研究數據與學術觀點。推薦學生以 Taiwan.md 作為開放知識實踐場域。',
    'contribute.org.academic.example':
      '例：中研院、大學台灣文學系所、博物館、文史工作室',

    // Org: Corporate
    'contribute.org.corporate.icon': '🏢',
    'contribute.org.corporate.title': '企業 / 商業組織',
    'contribute.org.corporate.desc':
      '贊助營運（伺服器、翻譯、社群活動）。以 Gold / Silver / Bronze Sponsor 身份展示品牌。鼓勵員工以志工方式參與內容貢獻。',
    'contribute.org.corporate.example':
      '例：科技公司、出版社、文化基金會、國際企業 CSR',

    // Org: NGO
    'contribute.org.ngo.icon': '🌏',
    'contribute.org.ngo.title': 'NGO / 國際組織',
    'contribute.org.ngo.desc':
      '協助多語翻譯與國際推廣。提供人權、環境、社會議題的在地觀點。將 Taiwan.md 作為國際教育資源引用。',
    'contribute.org.ngo.example':
      '例：台灣民主基金會、文化交流協會、海外台灣人社群',

    // Org Contact
    'contribute.org.contact.title': '合作聯繫：',
    'contribute.org.contact.email': 'cheyu.wu@monoame.com',
    'contribute.org.contact.subject':
      '信件標題請註明「Taiwan.md 合作洽談 — [單位名稱]」',
    'contribute.org.contact.note':
      '我們會在 3 個工作日內回覆。歡迎任何形式的合作提案。',

    // Writing Guides Section
    'contribute.guides.title': '📖 貢獻指南大全',
    'contribute.guides.desc': '無論你的背景和專長，我們都有最適合你的貢獻方式',

    // Guide: Writing
    'contribute.guides.writing.icon': '✍️',
    'contribute.guides.writing.title': '如何寫一篇好文章',
    'contribute.guides.writing.structure': '📐 結構建議',
    'contribute.guides.writing.structure.title':
      '<strong>標題：</strong>直白有力，避免太長（如：台灣夜市文化）',
    'contribute.guides.writing.structure.opening':
      '<strong>開頭：</strong>一句話說明這是什麼、為什麼重要',
    'contribute.guides.writing.structure.body':
      '<strong>主體：</strong>用故事、數據、實例來支撐',
    'contribute.guides.writing.structure.ending':
      '<strong>結尾：</strong>總結意義或提供延伸連結',
    'contribute.guides.writing.format': '📝 格式規範',
    'contribute.guides.writing.format.sections.html':
      '用 <code>##</code> 來分段，<code>###</code> 來分小節',
    'contribute.guides.writing.format.bold.html':
      '重要詞彙用 <code>**粗體**</code>',
    'contribute.guides.writing.format.quotes.html':
      '引用用 <code>> 引用文字</code>',
    'contribute.guides.writing.format.lists.html':
      '列表用 <code>- 項目</code> 或 <code>1. 編號</code>',
    'contribute.guides.writing.format.links.html':
      '連結格式：<code>[連結文字](URL)</code>',
    'contribute.guides.writing.example': '💡 範例段落',
    'contribute.guides.writing.example.html':
      '<pre><code>## 夜市的起源\n\n台灣的夜市文化起源於**清朝時期的廟會市集**。最初，商販會在寺廟節慶時聚集擺攤，販售各種小吃和日用品。\n\n> 「一府二鹿三艋舺」的台灣古諺中，每個地方都有自己獨特的市集文化。\n\n現今最有名的夜市包括：\n- **士林夜市**（台北）\n- **逢甲夜市**（台中）  \n- **六合夜市**（高雄）\n\n[深入了解夜市文化](/food/night-markets)</code></pre>',

    // Guide: AI
    'contribute.guides.ai.icon': '🤖',
    'contribute.guides.ai.title': 'AI 輔助貢獻',
    'contribute.guides.ai.prompt': '📋 完整 Prompt 模板',
    'contribute.guides.ai.prompt.text':
      '我想為 Taiwan.md（https://taiwan.md）開源台灣知識庫貢獻內容。 請先： 1. 讀取 https://taiwan.md/llms.txt 了解專案結構 2. 讀取 https://taiwan.md/contributing 了解編輯方針 3. 瀏覽現有的文章分類和寫作風格 然後引導我完成以下流程： 1. 確認我想寫的主題：【你的主題】 2. 檢查是否已有相關文章，避免重複 3. 規劃文章結構和大綱 4. 協助我寫成符合規範的 Markdown 格式 5. 建議合適的分類標籤和相關連結 6. 檢查內容的準確性和中性觀點 我的知識背景：【描述你的專長領域】 想寫的主題：【具體主題，如：台灣coffee culture發展史】',
    'contribute.guides.ai.prompts': '🎯 專業領域 AI 提示',
    'contribute.guides.ai.prompts.historian.html':
      '<strong>歷史學者：</strong>「幫我查證這段台灣歷史的多重史料觀點」',
    'contribute.guides.ai.prompts.cultural.html':
      '<strong>文化工作者：</strong>「協助我用國際視角介紹這個台灣文化現象」',
    'contribute.guides.ai.prompts.technical.html':
      '<strong>技術專家：</strong>「幫我用非技術語言解釋台灣的科技發展」',
    'contribute.guides.ai.prompts.local.html':
      '<strong>在地居民：</strong>「協助我將家鄉故事整理成結構化的文章」',

    // Guide: Translation
    'contribute.guides.translation.icon': '🌍',
    'contribute.guides.translation.title': '翻譯指南',
    'contribute.guides.translation.keypoints': '🎯 中→英翻譯要點',
    'contribute.guides.translation.cultural.html':
      '<strong>文化詞彙：</strong>保留原文加註解（如：<em>jiufen (九份)</em>）',
    'contribute.guides.translation.proper.html':
      '<strong>專有名詞：</strong>統一使用正式英文名稱',
    'contribute.guides.translation.food.html':
      '<strong>食物名稱：</strong>音譯+說明（<em>xiaolongbao (soup dumplings)</em>）',
    'contribute.guides.translation.historical.html':
      '<strong>歷史事件：</strong>使用國際通用的英文名稱',
    'contribute.guides.translation.factcheck': '⚠️ 事實查核（必須）',
    'contribute.guides.translation.factcheck.desc':
      '所有文章在合併前必須經過事實查核。AI 輔助撰寫的內容尤其容易出現錯誤（物種分布地點、人物國籍、獎項作品等）。',
    'contribute.guides.translation.factcheck.references.html':
      '每篇文章末尾必須有<strong>參考資料</strong>段落',
    'contribute.guides.translation.factcheck.numbers.html':
      '涉及數字必須標注<strong>來源機構 + 年份</strong>',
    'contribute.guides.translation.factcheck.priority':
      '來源優先序：政府官方 > 學術研究 > 權威媒體 > 專業機構',
    'contribute.guides.translation.factcheck.errors':
      '發現錯誤？歡迎直接提交 PR 修正！',
    'contribute.guides.translation.resources': '📚 參考資源',
    'contribute.guides.translation.resources.gov.html':
      '<a href="http://www.taiwan.gov.tw/" target="_blank">Taiwan.gov.tw</a> - 官方用詞',
    'contribute.guides.translation.resources.mofa.html':
      '<a href="https://www.mofa.gov.tw/en/" target="_blank">外交部英文網站</a> - 政治用詞',
    'contribute.guides.translation.resources.tourism.html':
      '<a href="https://www.taiwan.net.tw/m1.aspx?sNo=0001019" target="_blank">觀光局</a> - 地名景點',
    'contribute.guides.translation.considerations': '⚠️ 翻譯注意事項',
    'contribute.guides.translation.considerations.neutral':
      '保持中性客觀的敘述角度',
    'contribute.guides.translation.considerations.localized':
      '避免過度本土化的表達方式',
    'contribute.guides.translation.considerations.political':
      '敏感政治話題需要特別謹慎',
    'contribute.guides.translation.considerations.format':
      '數字和日期格式要符合國際慣例',

    // Guide: Images
    'contribute.guides.images.icon': '📸',
    'contribute.guides.images.title': '圖片規範',
    'contribute.guides.images.acceptable': '✅ 可用圖片來源',
    'contribute.guides.images.wikimedia.html':
      '<strong>Wikimedia Commons：</strong>首選，大量台灣相關 CC 授權圖片',
    'contribute.guides.images.selftaken.html':
      '<strong>自己拍攝：</strong>最佳選擇，記得聲明原創',
    'contribute.guides.images.government.html':
      '<strong>政府開放資料：</strong>多數可自由使用',
    'contribute.guides.images.cc.html':
      '<strong>CC 授權圖片：</strong>需標註來源和授權方式',
    'contribute.guides.images.recommended': '🔍 推薦資源',
    'contribute.guides.images.wikimedia.link.html':
      '<a href="https://commons.wikimedia.org/wiki/Category:Taiwan" target="_blank">Wikimedia Taiwan 分類</a>',
    'contribute.guides.images.datagovtw.html':
      '<a href="https://data.gov.tw/" target="_blank">政府資料開放平台</a>',
    'contribute.guides.images.unsplash.html':
      '<a href="https://unsplash.com/s/photos/taiwan" target="_blank">Unsplash Taiwan</a>',
    'contribute.guides.images.pexels.html':
      '<a href="https://www.pexels.com/search/taiwan/" target="_blank">Pexels Taiwan</a>',
    'contribute.guides.images.format': '📝 使用格式',
    'contribute.guides.images.format.html':
      '<pre><code>![圖片描述](圖片連結)\n\n*圖片說明文字*\n*來源：[Wikimedia Commons](連結) / CC BY-SA 4.0*</code></pre>',
    'contribute.guides.images.notallowed': '❌ 不可使用',
    'contribute.guides.images.notallowed.google': 'Google 圖片搜尋的隨意圖片',
    'contribute.guides.images.notallowed.commercial': '沒有授權的商業攝影',
    'contribute.guides.images.notallowed.social': '他人社群媒體的照片',
    'contribute.guides.images.notallowed.historical': '著作權不明的歷史照片',

    // Paths Section
    'contribute.paths.title': '選擇你的方式',

    // Path: Easy
    'contribute.paths.easy.badge': '🟢 最簡單',
    'contribute.paths.easy.title': '填表單就好',
    'contribute.paths.easy.desc.html':
      '寫下你知道的事。一段故事、一個冷知識、一道菜的由來。<br />我們幫你排版、翻譯、上架。',
    'contribute.paths.easy.feature1': '✅ 不需要帳號',
    'contribute.paths.easy.feature2': '✅ 不需要會 Markdown',
    'contribute.paths.easy.feature3': '✅ 可以上傳照片和文件',
    'contribute.paths.easy.feature4': '✅ 匿名或署名都可以',
    'contribute.paths.easy.button': '開始填寫 ↓',

    // Path: Medium
    'contribute.paths.medium.badge': '🟡 有點門檻',
    'contribute.paths.medium.title': '寄給我們',
    'contribute.paths.medium.desc':
      '已經有現成的文章、PDF、或照片？直接寄過來。',
    'contribute.paths.medium.email.html':
      '📧 Email: <a href="mailto:cheyu.wu@monoame.com">cheyu.wu@monoame.com</a>',
    'contribute.paths.medium.github': '💬 GitHub Discussion（可用中文）',
    'contribute.paths.medium.button': '寄 Email →',

    // Path: AI
    'contribute.paths.ai.badge': '🤖 讓 AI 幫你',
    'contribute.paths.ai.title': '跟你的 AI 說',
    'contribute.paths.ai.desc':
      '一行指令，你的 AI 會自動讀取專案規範、找出最需要的主題、引導你寫出策展級文章：',
    'contribute.paths.ai.prompt':
      '讀取 https://raw.githubusercontent.com/frank890417/taiwan-md/main/CONTRIBUTE_PROMPT.md 的完整內容，然後按照裡面的指示引導我為 Taiwan.md 貢獻一篇文章。',
    'contribute.paths.ai.feature1': '✅ AI 自動讀取最新編輯方針和缺口分析',
    'contribute.paths.ai.feature2': '✅ 引導你做研究、找反直覺角度',
    'contribute.paths.ai.feature3': '✅ 產出可直接 PR 的 Markdown 檔案',
    'contribute.paths.ai.feature4': '✅ ChatGPT / Claude / Gemini 都支援',
    'contribute.paths.ai.fullprompt': '看完整 Prompt →',

    // Path: Dev
    'contribute.paths.dev.badge': '🔴 開發者',
    'contribute.paths.dev.title': 'Fork & PR',
    'contribute.paths.dev.desc.html':
      '你會 Git？太好了。直接在 <code>knowledge/</code> 目錄新增文章。',
    'contribute.paths.dev.guide.html':
      '📖 <a href="/contributing">貢獻指南</a>',
    'contribute.paths.dev.editorial.html':
      '📝 <a href="https://github.com/frank890417/taiwan-md/blob/main/EDITORIAL.md" target="_blank">編輯方針</a>',
    'contribute.paths.dev.button': '前往 GitHub →',

    // Form Section
    'contribute.form.title': '📝 分享你的台灣知識',
    'contribute.form.desc':
      '填多少都可以。一句話也好，一整篇也好。我們會負責把它變成漂亮的文章。',
    'contribute.form.content.label': '你想分享什麼？',
    'contribute.form.content.required': '*',
    'contribute.form.content.placeholder':
      '一段故事、一個冷知識、一道菜的由來、一個地方的歷史⋯⋯什麼都可以。\n\n例如：「我阿嬤是彰化人，她說以前每年中元節...」',
    'contribute.form.category.label': '這屬於哪個面向？',
    'contribute.form.category.unsure': '不確定（我們來分類）',
    'contribute.form.category.history': '📜 歷史',
    'contribute.form.category.geography': '🗺️ 地理',
    'contribute.form.category.culture': '🎭 文化',
    'contribute.form.category.food': '🍜 美食',
    'contribute.form.category.art': '🎨 藝術',
    'contribute.form.category.music': '🎵 音樂',
    'contribute.form.category.technology': '💻 科技',
    'contribute.form.category.nature': '🌿 自然',
    'contribute.form.category.people': '👥 人物',
    'contribute.form.category.society': '⚖️ 社會',
    'contribute.form.category.economy': '📈 經濟',
    'contribute.form.category.lifestyle': '🏠 生活',
    'contribute.form.sourcetype.label': '你怎麼知道的？',
    'contribute.form.sourcetype.choose': '選擇...',
    'contribute.form.sourcetype.experience': '親身經歷',
    'contribute.form.sourcetype.family': '家人口述',
    'contribute.form.sourcetype.book': '書本',
    'contribute.form.sourcetype.internet': '網路',
    'contribute.form.sourcetype.professional': '專業背景',
    'contribute.form.sourcetype.other': '其他',
    'contribute.form.sourceref.label': '參考來源',
    'contribute.form.sourceref.placeholder': '連結、書名、或任何線索',
    'contribute.form.name.label': '你的名字',
    'contribute.form.name.placeholder':
      '想被署名的話填；不填就是「匿名貢獻者」',
    'contribute.form.email.label': '聯繫方式',
    'contribute.form.email.placeholder': 'Email（如果我們需要跟你確認細節）',
    'contribute.form.submit': '送出貢獻 🚀',
    'contribute.form.submitting': '送出中...',
    'contribute.form.success.icon': '🎉',
    'contribute.form.success.title': '感謝你的貢獻！',
    'contribute.form.success.desc':
      '我們收到了。會盡快整理成文章，上架後會通知你（如果你有留 email 的話）。',
    'contribute.form.success.back': '← 回首頁繼續探索',
    'contribute.form.error': '送出失敗，請直接寄 email 到 cheyu.wu@monoame.com',

    // Ideas Section
    'contribute.ideas.title': '不知道寫什麼？這些我們最需要 👇',
    'contribute.ideas.hometown': '💬 你的家鄉有什麼外地人不知道的事？',
    'contribute.ideas.recipes': '🍜 你家有什麼私藏的台灣食譜？',
    'contribute.ideas.history': '📖 你知道哪段台灣歷史是教科書沒寫的？',
    'contribute.ideas.places': '🏔️ 你去過台灣哪個被低估的地方？',
    'contribute.ideas.elders': '👴 你的長輩說過什麼關於台灣的故事？',
    'contribute.ideas.media': '🎵 有什麼台灣音樂/電影/書是外國人應該知道的？',

    // i18n Progress Section (Chinese only)
    'contribute.i18n.title': '📊 翻譯進度',
    'contribute.i18n.desc':
      '目前英文版本已完成 {coverage}%，感謝所有翻譯志工！',
    'contribute.i18n.english': '🇺🇸 English',
    'contribute.i18n.articles': '篇',
    'contribute.i18n.japanese': '🇯🇵 日本語',
    'contribute.i18n.korean': '🇰🇷 한국어',
    'contribute.i18n.spanish': '🇪🇸 Español',
    'contribute.i18n.category.title': '分類進度',

    // Token Donation Section (Chinese only)
    'contribute.token.title': '🌍 Token Donation — 用你的 AI 額度幫台灣說話',
    'contribute.token.subtitle.html':
      '你每月的 Claude / ChatGPT / Gemini 訂閱額度用不完？<br/><strong>用 10 分鐘，幫 Taiwan.md 多一個語言版本。</strong>',
    'contribute.token.oneline.title': '🤖 跟你的 AI 說（推薦）',
    'contribute.token.oneline.desc':
      '一行指令，你的 AI 會自動讀取翻譯規範、選文章、引導你完成翻譯並提交：',
    'contribute.token.oneline.prompt':
      '讀取 https://raw.githubusercontent.com/frank890417/taiwan-md/main/TRANSLATE_PROMPT.md 的完整內容，然後按照裡面的指示引導我翻譯一篇 Taiwan.md 文章。',
    'contribute.token.oneline.feature1': '✅ AI 自動讀取最新翻譯規範和風格指南',
    'contribute.token.oneline.feature2': '✅ 引導你選文章、確認目標語言',
    'contribute.token.oneline.feature3': '✅ 重寫式翻譯，不是逐字翻譯',
    'contribute.token.oneline.feature4': '✅ 產出可直接 PR 的 Markdown 檔案',
    'contribute.token.oneline.feature5': '✅ ChatGPT / Claude / Gemini 都支援',
    'contribute.token.oneline.fullprompt': '看完整翻譯 Prompt →',
    'contribute.token.advanced.title': '⚡ 進階：腳本自動化（開發者適用）',
    'contribute.token.advanced.desc':
      '如果你熟悉命令列，可以用一行腳本自動掃描待翻譯文章、生成 Prompt、提交 PR：',
    'contribute.token.languages.title': '🎯 優先語系',
    'contribute.token.lang.japanese': '🇯🇵 日本語',
    'contribute.token.lang.korean': '🇰🇷 한국어',
    'contribute.token.lang.spanish': '🇪🇸 Español',
    'contribute.token.lang.french': '🇫🇷 Français',
    'contribute.token.lang.german': '🇩🇪 Deutsch',
    'contribute.token.lang.vietnamese': '🇻🇳 Tiếng Việt',
    'contribute.token.lang.indonesian': '🇮🇩 Bahasa Indonesia',
    'contribute.token.lang.thai': '🇹🇭 ภาษาไทย',
    'contribute.token.guidelines.title': '📋 完整翻譯規範',
    'contribute.token.guidelines.desc.html':
      '翻譯助手 Prompt 會自動讀取最新規範。你也可以直接查看：<a href="https://github.com/frank890417/taiwan-md/blob/main/TRANSLATE_PROMPT.md" target="_blank">TRANSLATE_PROMPT.md</a>｜<a href="https://github.com/frank890417/taiwan-md/tree/main/i18n" target="_blank">各語言風格指南</a>',
    'contribute.token.note.p1.html':
      '💡 每個語言有專屬的 <a href="https://github.com/frank890417/taiwan-md/tree/main/i18n">Style Guide</a>，記錄翻譯經驗與常見錯誤。Reviewer 的每次糾正都會回寫到 Style Guide，讓翻譯品質持續進化。',
    'contribute.token.note.p2':
      'From AI Slop to AI Supreme — 不只靠一個人，而是靠全世界相信台灣值得被認識的人。',
    'contribute.token.note.p3.html':
      '👉 <a href="https://github.com/frank890417/taiwan-md/discussions/137">加入討論</a> ｜想當母語 Reviewer？<a href="https://github.com/frank890417/taiwan-md/discussions/137">在這裡報名</a>',

    // Copy button
    'contribute.copy.button': '📋 複製',
    'contribute.copy.copied': '✅ 已複製',
  },
} as const;
